Believe I finished the acceptance criteria of this issue
ucsb-cs156-w22/team04-w22-7pm-courses pull request #22
Opened 2022-03-05 01:49 UTC by ericxu002

Look at comments for my branch

2022-03-05 01:55 UTC, ericxu002 commented
okay actually, don't merge this at all there are failed tests that I need to resolve and I'll keep this open so I use this as a reminder of where and what to fix

2022-03-08 01:25 UTC, WAKACHUU submitted a review, later dismissed
LGTM

2022-03-08 05:32 UTC, rithwikadicherla approved these changes, later dismissed
LGTM

2022-03-08 05:34 UTC, WAKACHUU submitted a review, later dismissed
LGTM

2022-03-08 09:22 UTC, rithwikadicherla submitted a review, later dismissed
LGTM

2022-03-08 21:32 UTC, pconrad requested changes
The staff cannot code review this unless/until it is:
* Linked properly to an issue
* Title and description are fixed.

2022-03-09 21:10 UTC, pconrad requested changes
Please remove commented out code.

2022-03-09 21:10 UTC, pconrad commented on frontend/src/main/components/Level/LevelDropdown.js
> +                <option key = {"All"} label = "All" value="All"></option>; */}
Can we remove this commented out code?

2022-03-09 21:10 UTC, pconrad commented on frontend/src/main/components/SubmitButton/SubmitButton.js
> +        //<Form onSubmit={handleSubmit(submitAction)}>
Can we remove this commented out line?

2022-03-09 21:10 UTC, pconrad commented on frontend/src/main/components/SubmitButton/SubmitButton.js
> +        //</Form>
Can we remove this commented out line?

2022-03-09 21:10 UTC, pconrad commented on frontend/src/stories/components/Level/LevelDropdown.stories.js
> +//EX: DO I EVEN NEED THE IMPORT ABOVE FOR UTILITIES FOR OUR LEVEL DROPDOWN BECAUSE IM NOT CHANGING ANYTHING
I'm guessing: no?   Since they are commented out and everything is working?  So let's remove this.

2022-03-09 21:10 UTC, pconrad commented on frontend/src/stories/components/Level/LevelDropdown.stories.js
> +// };
Are the levels hard coded in the component, or injected into the component?  If the component has no props, and shows up correctly i the storybook, you don't need this, and should remove it.

2022-03-09 21:10 UTC, pconrad commented on frontend/src/tests/components/SubmitButton/SubmitButton.test.js
> +        // axiosMock.onGet("/api/systemInfo").reply(200, systemInfoFixtures.showingNeither);
Remove commented out code.

2022-03-09 21:10 UTC, pconrad commented on frontend/src/tests/components/SubmitButton/SubmitButton.test.js
> +        // const inactiveField = getByTestId("UCSBSubjectForm-inactive");
Remove commented out code.

2022-03-09 21:36 UTC, rithwikadicherla approved these changes
LGTM

2022-03-10 01:48 UTC, WAKACHUU approved these changes
LGTM

2022-03-10 18:44 UTC, pconrad approved these changes
LGTM

2022-03-10 18:44 UTC, merged