made table and fixture and limit the word with description
ucsb-cs156-w22/team04-w22-7pm-courses pull request #31
Opened 2022-03-09 03:23 UTC by binyuzhong

# Overview

In a sentence or two, provide an overview of how this pull request updates the main branch.  You may use a bullet list if that helps.

# Issues Addressed

If this PR closes or deals with issues, mention them and tag the issue number with the `#` syntax.

# Details

Where applicable, include "before" and "after" screenshots or animated GIFs.   The tool [LiceCAP](https://www.cockos.com/licecap/) or one of [these similar tools](https://www.nextofwindows.com/5-free-tools-to-screen-capture-to-gif-on-windows) 
can be used to capture screenshots/animated GIFs.

## Reminders (delete this section before merging or as code is merged)
- [ ] Explicitly link to this pull request each issue that it closes
- [ ] Assign one and ideally two reviewers to review this pull request. 
- [ ] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

2022-03-10 00:08 UTC, pconrad requested changes

2022-03-10 00:08 UTC, pconrad commented on frontend/src/main/components/Courses/CoursesTable.js
> +    // Stryker disable ArrayDeclaration : [columns] and [students] are performance optimization; mutation preserves correctness
[students] should be [courses] in the comment

2022-03-10 01:11 UTC, ericxu002 submitted a review, later dismissed
LGTM!

2022-03-10 01:19 UTC, WAKACHUU submitted a review, later dismissed
LGTM

2022-03-11 03:05 UTC, pconrad submitted a review, later dismissed
LGTM

2022-03-11 09:56 UTC, andrewhlu commented on frontend/src/fixtures/coursesFixtures.js
> +            "description": "The nature of culture: survey of the range of cultural phenomena, including material culture, social organization, religion, and other topics.he nature of culture: survey
A small copy-paste error I noticed. It would be great if you fixed this - you can either do it here or in a separate PR.
```suggestion
            "description": "The nature of culture: survey of the range of cultural phenomena, including material culture, social organization, religion, and other topics. The nature of culture: survey of the range of cultural phenomena, including material culture, social organization, religion, and other topics. The nature of culture: survey of the range of cultural phenomena, including material culture, social organization, religion, and other topics",
```

2022-03-11 09:56 UTC, andrewhlu commented on frontend/src/main/components/Courses/CoursesTable.js
> +
I don't think all this whitespace is necessary?
```suggestion

export default function CoursesTable({ courses, currentUser }) {
    const limitText = ({value})=>{
        return value.substr(0,150);
```

2022-03-11 23:57 UTC, ericxu002 approved these changes
LGTM

2022-03-11 23:57 UTC, WAKACHUU approved these changes
LGTM

2022-03-12 03:26 UTC, pconrad approved these changes
LGTM---will test on storybook

2022-03-12 03:28 UTC, merged